### ISSUE TITLE
Latest release build breaks opkg

### ISSUE THREAD

**Issue by devlux76** [friendlyarm/Actions-FriendlyWrt#1]
`
root@Web-01:~# opkg update
Downloading https://downloads.openwrt.org/releases/22.03.0/packages/aarch64_generic/base/Packages.gz
Updated list of available packages in /opt/opkg-lists/openwrt_base
Downloading https://downloads.openwrt.org/releases/22.03.0/packages/aarch64_generic/luci/Packages.gz
Updated list of available packages in /opt/opkg-lists/openwrt_luci
Downloading https://downloads.openwrt.org/releases/22.03.0/packages/aarch64_generic/packages/Packages.gz
Updated list of available packages in /opt/opkg-lists/openwrt_packages
Downloading https://downloads.openwrt.org/releases/22.03.0/packages/aarch64_generic/routing/Packages.gz
Updated list of available packages in /opt/opkg-lists/openwrt_routing
Downloading https://downloads.openwrt.org/releases/22.03.0/packages/aarch64_generic/telephony/Packages.gz
Updated list of available packages in /opt/opkg-lists/openwrt_telephony
Downloading file://opt/packages/Packages.gz
*** Failed to download the package list from file://opt/packages/Packages.gz

Collected errors:
 * copy_file: //opt/packages/Packages.gz: No such file or directory.
 * file_copy: Failed to copy file //opt/packages/Packages.gz to /opt/opkg-lists/friendlywrt_packages.
`

**Comment by devlux76** [comment]
Commenting out the final line in 
/etc/opkg/distfeeds.conf

Resolves it, but perhaps some post install cleanup is in order?

**Comment by friendlyarm** [comment]
Already fixed, thank you for your feedback!
