### ISSUE TITLE
Docker / Root Overlay Inode Issue

### ISSUE THREAD

**Issue by websi96** [friendlyarm/Actions-FriendlyWrt#12]
Hi!

I currently try to get docker and dind working on the R6S and came across inode issues on the extended overly rootfs:

```sh
$ df -hi

Filesystem     Inodes IUsed IFree IUse% Mounted on
tmpfs            960K   194  959K    1% /dev
tmpfs            960K   312  959K    1% /run
overlay           57K   57K   232  100% /
tmpfs            960K  1.6K  958K    1% /tmp
cgroup           960K    13  960K    1% /sys/fs/cgroup
```

Any idea on how to increase the inode size? Afaik friendlywrt extends the rootfs on it's first boot right?

Kind regards,
Thomas

**Comment by friendlyarm** [comment]
I have built a test image,  try it and see if the issue has been solved:
https://drive.google.com/drive/folders/1TY85WaCvD9xpeDPW2AReJvnIvinhGzHW?usp=share_link

I tested that calling the following command works: 
docker pull jpetazzo/dind

**Comment by friendlyarm** [comment]
In the test Image, I added this option to the kernel config: CONFIG_OVERLAY_FS_META_COPY=y

**Comment by websi96** [comment]
I used the last release and it is fixed now:

```shell
$ df -hi

Filesystem     Inodes IUsed IFree IUse% Mounted on
tmpfs            960K   194  959K    1% /dev
tmpfs            960K   309  959K    1% /run
overlay          1.4M   190  1.4M    1% /
tmpfs            960K  1.6K  958K    1% /tmp
cgroup           960K    13  960K    1% /sys/fs/cgroup
```

thank you very much! 👍
