### ISSUE TITLE
R5C机器，friendlywrt-22.03固件，外接SSD硬盘一直报reset SuperSpeed Gen 1 USB device number 8 using xhci-hcd的警告

### ISSUE THREAD

**Issue by antbuster** [friendlyarm/Actions-FriendlyWrt#26]
R5C机器，friendlywrt-22.03固件，
外接SSD硬盘一直报reset SuperSpeed Gen 1 USB device number 8 using xhci-hcd的警告，时间一久就掉盘，同一硬盘盒接HHD就没事。
接PC一点事情都没有。

**Comment by lawrencetg** [comment]
加载UAS模块试试：
echo "uas" > /etc/modules.d/uas
reboot
