### ISSUE TITLE
R5C默认固件网络存储菜单没了

### ISSUE THREAD

**Issue by xjpz** [friendlyarm/Actions-FriendlyWrt#33]
不知道是不是因为在[系统]--[备份与升级]里重置了导致上面的[网络存储](NAS)菜单没了。

另外问下发新包了能通过[备份与升级]-[刷新新的固件]保存配置升级吗？

**Comment by lawrencetg** [comment]
可以这样升级固件：
1） 进入 “系统” -> "备份与升级" -> "生成备份”，会下载一个压缩包到电脑上
2）刷写新固件
3）新固件开机后再 进入 “系统” -> "备份与升级"，点 “上传备份”，上传步骤1的压缩包

**Comment by xjpz** [comment]
好
