### ISSUE TITLE
MT7922什么时候支持

### ISSUE THREAD

**Issue by github-mutech** [friendlyarm/Actions-FriendlyWrt#35]
大佬们，MT7922什么时候支持？🙏🏻

**Comment by friendlyarm** [comment]
测试过 2023-06-10 的固件了吗？ 这个版本整合了MT79xx的驱动和固件进去了

**Comment by github-mutech** [comment]
> 测试过 2023-06-10 的固件了吗？ 这个版本整合了MT79xx的驱动和固件进去了

晚上回去试试，更新日志还以为只有7921，感谢
