### ISSUE TITLE
⚠️ GitHub release failed with status: 403

### ISSUE THREAD

**Issue by nioet7** [friendlyarm/Actions-FriendlyWrt#36]
Run softprops/action-gh-release@v1
👩‍🏭 Creating new GitHub release for tag FriendlyWrt-2023-06-23...
⚠️ GitHub release failed with status: 403
undefined
retrying... (2 retries remaining)
👩‍🏭 Creating new GitHub release for tag FriendlyWrt-2023-06-23...
⚠️ GitHub release failed with status: 403
undefined
retrying... (1 retries remaining)
👩‍🏭 Creating new GitHub release for tag FriendlyWrt-2023-06-23...
⚠️ GitHub release failed with status: 403
undefined
retrying... (0 retries remaining)
❌ Too many retries. Aborting...
Error: Too many retries.

**Comment by friendlyarm** [comment]
https://github.com/softprops/action-gh-release/issues/236
