### ISSUE TITLE
r5c 12月的 23.05 docker 固件，断电重启，系统log和docker log全部乱码...

### ISSUE THREAD

**Issue by gowy222** [friendlyarm/Actions-FriendlyWrt#45]
系统log:
`Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005218] 3870  00000000 00000000 00000000 00000000 00000000 00000000 0329a8c0 d7dfa3b4
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005249] 3890  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005279] 38b0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005312]
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005312] X3: 0xffff800008003898:
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005321] 3698  000000c0 00000000 00000000 00000000 0a27e7c0 ffff8000 080036d0 ffff8000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005352] 36b8  08e10434 ffff8000 00000000 00000000 f0d40000 ffff0001 08003800 ffff8000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005384] 36d8  08f4df88 ffff8000 035ee500 ffff0000 00000001 00000000 00000000 00000000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005414] 36f8  0a27e7c0 ffff8000 f137da80 ffff0001 0329a8c0 00000000 00000001 00000000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005446] 3718  f0d40000 ffff0001 08003a38 ffff8000 08003c48 ffff8000 00000004 ffff8000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005479] 3738  0329a8c0 00000000 00000000 00000000 0a27e7c0 ffff8000 000000ff 00000000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005511] 3758  0329a8c0 fe020020 00000000 00000000 f2631980 ffff0001 f2631900 ffff0001
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005543] 3778  f2684d00 00080001 03aa3028 ffff0000 00000000 00000000 00000000 00000000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005574] 3798  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005605] 37b8  00000000 0329a8c0 00000000 00000000 9806a000 6fcf3029 08003800 ffff8000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005636] 37d8  08f4e064 ffff8000 035ee500 ffff0000 9806a000 6fcf3029 00000004 00000000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005666] 37f8  030f4088 ffff0000 080038f0 ffff8000 022fe578 ffff8000 035ee500 ffff0000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005699] 3818  030ca000 ffff0000 03789eea ffff0000 0a27e7c0 ffff8000 00000000 00000000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005730] 3838  00000000 00000000 0232d4d0 ffff8000 030f4088 ffff0000 080038a0 ffff8000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005761] 3858  00000000 00000000 00000000 00000000 01000000 00000000 00000000 00000000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005791] 3878  00000000 00000000 00000000 00000000 0329a8c0 d7dfa3b4 00000000 00000000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005822] 3898* 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005852] 38b8  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005882] 38d8  00000000 00000000 00000000 00000000 9806a000 6fcf3029 08003950 ffff8000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005913] 38f8  022540e8 ffff8000 08003c48 ffff8000 08003a38 ffff8000 0232d448 ffff8000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005945] 3918  0232d000 ffff8000 030f40e0 ffff0000 030f40c8 ffff0000 08003980 ffff8000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.005977] 3938  08f44cd0 ffff8000 08003980 ffff8000 9806a000 6fcf3029 08003980 ffff8000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.006009] 3958  02306228 ffff8000 030f40b8 ffff0000 0232d780 ffff8000 030f4090 ffff0000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.006041] 3978  0232d780 ffff8000 08003c10 ffff8000 0231a2fc ffff8000 f032d850 ffff0001
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.006072] 3998  00000001 00000000 f20ab800 ffff0001 030ca000 ffff0000 08003cd8 ffff8000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.006102] 39b8  ff6b2f68 ffff0001 ff6bae50 ffff0001 00000000 00000000 ff6bae40 ffff0001
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.006132] 39d8  09e546c0 ffff8000 00000004 ffff0001 f20ec180 ffff0001 00000003 00000001
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.006163] 39f8  f032d850 ffff0001 00000000 00000000 08003c00 ffff8000 f3360000 ffff0001
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.006194] 3a18  00000000 00000000 00000000 00000000 f47b8600 ffff0001 0a27e7c0 ffff8000
Fri Feb  2 23:21:07 2024 kern.warn kernel: [   48.006224] 3a38  ffffffff 00000000 f20ec180 ffff0001 00000006 00000000 00000000 00000000。。。
Fri Feb  2 23:25:19 2024 daemon.err dockerd[3916]: time="2024-02-02T15:25:19.538803558Z" level=error msg="Error streaming logs: invalid character '\\x00' looking for beginning of value" container=99b1e6cc69180002c102afa1186947e1e4341f9351c190e80a46684b44ec60a7 method="(*Daemon).ContainerLogs" module=daemon
Fri Feb  2 23:25:24 2024 daemon.err dockerd[3916]: time="2024-02-02T15:25:24.179433055Z" level=error msg="Error streaming logs: invalid character '\\x00' looking for beginning of value" container=99b1e6cc69180002c102afa1186947e1e4341f9351c190e80a46684b44ec60a7 method="(*Daemon).ContainerLogs" module=daemon
`
docker 容器 也是 开机自起，然后容器虽然正常工作，但是log全是乱码...
路由没办法防止断电重启，这块有办法通电开机优化？比如 清理意外当机缓存碎片啥...？

**Comment by friendlyarm** [comment]
这是串口打印的日志吗？ 是不是串口终端退出重进就可以了（重置一下串口终端）
