### ISSUE TITLE
R2S Nftables Qos Not Working

### ISSUE THREAD

**Issue by adibindrianto** [friendlyarm/Actions-FriendlyWrt#47]
How to fix nftables qos limit bandwith friendlywrt 23.05.02 update february, do you have solution?

**Comment by adibindrianto** [comment]
please update to openwrt 23.05.3  latest version, thanks

**Comment by friendlyarm** [comment]
> please update to openwrt 23.05.3 latest version, thanks

it's done :)

**Comment by adibindrianto** [comment]
how to fix nft qos not working? openwrt 23.05.03, any solution?

**Comment by adibindrianto** [comment]
Do you have an alternative qos limit per client?

**Comment by lawrencetg** [comment]
We'll test it and get back to you.

**Comment by adibindrianto** [comment]
I really hope this can be implemented soon

**Comment by adibindrianto** [comment]
> We'll test it and get back to you.

any updates?

**Comment by friendlyarm** [comment]
> > We'll test it and get back to you.
> 
> any updates?

I tested the image R2S-R2C-Series-FriendlyWrt-23.05.img.gz, nft-qos is working properly. You need to disable software offload because it is incompatible with QoS. To disable it, go to the Firewall page and uncheck the option "Software flow offloading".
