### ISSUE TITLE
How Change Default IP Address

### ISSUE THREAD

**Issue by adibindrianto** [friendlyarm/Actions-FriendlyWrt#49]
How to change the default FriendlyWRT ip address 192.168.2.1 to 192.168.1.1? I have used your fork but it's hard for me to understand it

**Comment by lawrencetg** [comment]
Refer to the following change:
```
diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
index bf5312f..24f9859 100644
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -79,6 +79,8 @@ jobs:
         cd project
         source ../scripts/add_packages.sh
         source ../scripts/custome_config.sh
+        sed -i 's/192.168.2.1/192.168.1.1/g' \
+            friendlywrt/target/linux/rockchip/armv8/base-files/etc/board.d/02_network

     - name: Prepare dot config and feeds
       run: |
```

**Comment by adibindrianto** [comment]
- name: Apply customizations
      run: |
        cd project
        source ../scripts/add_packages.sh
        source ../scripts/custome_config.sh
        sed -i 's/192.168.2.1/192.168.1.1/g' \
        friendlywrt/target/linux/rockchip/armv8/base-files/etc/board.d/02_network

i just copy from workflows, like this?

**Comment by lawrencetg** [comment]
Add space indent before friendlywrt, or write it on one line
```
    - name: Apply customizations
      run: |
        cd project
        source ../scripts/add_packages.sh
        source ../scripts/custome_config.sh
        sed -i 's/192.168.2.1/192.168.1.1/g' friendlywrt/target/linux/rockchip/armv8/base-files/etc/board.d/02_network
```

**Comment by adibindrianto** [comment]
I will confirm after completing the process
