### ISSUE TITLE
R5S  没有 eMMC 刷机助手

### ISSUE THREAD

**Issue by lv-3** [friendlyarm/Actions-FriendlyWrt#5]
R5S  没有 eMMC 刷机助手
---
如图:

![图片](https://user-images.githubusercontent.com/12018747/202179591-fa4973bc-04e4-4e69-9c8b-21e2883a921d.png)

系统下面没有 "eMMC 刷机助手", 是取消了该功能, 还是出现故障?

如何判定?

**Comment by friendlyarm** [comment]
只在从 SD 卡启动系统时， eMMC 刷机助手才会出现

**Comment by tkfanswind** [comment]
eMMC 刷机助手在software里面是哪个ipk?为啥我搜索不到
我是R3S以前用eMMC启动的时候能看到eMMC 刷机助手.
R3S如何控制用SD卡启动?我的eMMC卡是ImmortalWrt.
