### ISSUE TITLE
不管什么插件Tproxy模式开启网络就爆炸

### ISSUE THREAD

**Issue by Alexrobot03** [friendlyarm/Actions-FriendlyWrt#6]
R6s

**Comment by friendlyarm** [comment]
使用非docker的版本试试，docker会对网络设置影响，需要小心处理

**Comment by Alexrobot03** [comment]
一直用的非docker版本，

**Comment by Alexrobot03** [comment]
试了最新的固件v2raya的Tproxy 模式还是不能用，开启只有udp流量，无法转发tcp，shellclash也是一样![image](https://user-images.githubusercontent.com/114252170/203977026-57b50d2d-fbb9-4831-a1b3-137c36ad624d.jpeg)

**Comment by friendlyarm** [comment]
试试这个方法管不管用

echo "net.bridge.bridge-nf-call-iptables=0" > /etc/sysctl.d/32-iptables-user.conf
reboot

**Comment by Alexrobot03** [comment]
不行> 试试这个方法管不管用
> 
> 
> 
> echo "net.bridge.bridge-nf-call-iptables=0" > /etc/sysctl.d/32-iptables-user.conf
> 
> reboot

**Comment by leiusual** [comment]
> 试试这个方法管不管用
> 
> echo "net.bridge.bridge-nf-call-iptables=0" > /etc/sysctl.d/32-iptables-user.conf reboot

这个管用
