### ISSUE TITLE
sdk更新软件包报错

### ISSUE THREAD

**Issue by ksi1110** [friendlyarm/Actions-FriendlyWrt#68]
![image](https://github.com/user-attachments/assets/7dcb83ce-0e70-4666-ab00-6763a36a0b40)

我按照官方文档尝试自己编译固件，在更新包之前运行命令都没问题，更新包时出现错误，没有master-v23.05。
求助帮忙解决
官方教程：
![image](https://github.com/user-attachments/assets/de49bc2e-4d27-44c0-a8a1-729356cb3ea2)

我使用的sdk：
![image](https://github.com/user-attachments/assets/8c3b24f0-99d5-41b7-86bc-741826e5fae0)

**Comment by ksi1110** [comment]
命令跑完了，基本上都报错，具体日志如下：
ubuntu@ubuntu:/mnt/sdk$ ./scripts/feeds update -a
Updating feed 'base' from 'https://git.openwrt.org/openwrt/openwrt.git;master-v23.05' ...
Cloning into './feeds/base'...
fatal: Remote branch master-v23.05 not found in upstream origin
failed.
Updating feed 'packages' from 'https://git.openwrt.org/feed/packages.git^0da9f622975aa1e4efe452da4acbae15479bee63' ...
Cloning into './feeds/packages'...
remote: Enumerating objects: 208717, done.
remote: Counting objects: 100% (208717/208717), done.
remote: Compressing objects: 100% (87962/87962), done.
error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
failed.
Updating feed 'luci' from 'https://git.openwrt.org/project/luci.git^257f54cb8bcd493d9be0a45a3c316668b793e8ae' ...
Cloning into './feeds/luci'...
remote: Enumerating objects: 38855, done.
remote: Counting objects: 100% (38855/38855), done.
remote: Compressing objects: 100% (6308/6308), done.
error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
failed.
Updating feed 'routing' from 'https://git.openwrt.org/feed/routing.git^2272106e0839ee06957e88e3596489e1b510d3c2' ...
Cloning into './feeds/routing'...
remote: Enumerating objects: 11448, done.
remote: Counting objects: 100% (11448/11448), done.
remote: Compressing objects: 100% (6954/6954), done.
remote: Total 11448 (delta 5271), reused 9082 (delta 3826), pack-reused 0
Receiving objects: 100% (11448/11448), 2.62 MiB | 2.02 MiB/s, done.
Resolving deltas: 100% (5271/5271), done.
Switched to a new branch '2272106e0839ee06957e88e3596489e1b510d3c2'
/mnt/sdk
Updating feed 'telephony' from 'https://git.openwrt.org/feed/telephony.git^9746ae8f964e18f04b64fbe1956366954ff223f8' ...
Cloning into './feeds/telephony'...
remote: Enumerating objects: 11912, done.
remote: Counting objects: 100% (11912/11912), done.
remote: Compressing objects: 100% (7283/7283), done.
remote: Total 11912 (delta 6704), reused 8140 (delta 4394), pack-reused 0
Receiving objects: 100% (11912/11912), 2.40 MiB | 1.79 MiB/s, done.
Resolving deltas: 100% (6704/6704), done.
Switched to a new branch '9746ae8f964e18f04b64fbe1956366954ff223f8'
/mnt/sdk
Create index file './feeds/base.index' 
Checking 'true'... ok.
Checking 'false'... ok.
Checking 'working-make'... ok.
Checking 'case-sensitive-fs'... ok.
Checking 'proper-umask'... ok.
Checking 'gcc'... ok.
Checking 'working-gcc'... ok.
Checking 'g++'... ok.
Checking 'working-g++'... ok.
Checking 'ncurses.h'... ok.
Checking 'git'... ok.
Checking 'rsync'... ok.
Checking 'perl-data-dumper'... ok.
Checking 'perl-findbin'... ok.
Checking 'perl-file-copy'... ok.
Checking 'perl-file-compare'... ok.
Checking 'perl-thread-queue'... ok.
Checking 'tar'... ok.
Checking 'find'... ok.
Checking 'bash'... ok.
Checking 'xargs'... ok.
Checking 'patch'... ok.
Checking 'diff'... ok.
Checking 'cp'... ok.
Checking 'seq'... ok.
Checking 'awk'... ok.
Checking 'grep'... ok.
Checking 'egrep'... ok.
Checking 'getopt'... ok.
Checking 'realpath'... ok.
Checking 'stat'... ok.
Checking 'gzip'... ok.
Checking 'unzip'... ok.
Checking 'bzip2'... ok.
Checking 'wget'... ok.
Checking 'install'... ok.
Checking 'perl'... ok.
Checking 'python'... ok.
Checking 'python3'... ok.
Checking 'python3-distutils'... ok.
Checking 'python3-stdlib'... ok.
Checking 'file'... ok.
Checking 'which'... ok.
Checking 'argp.h'... ok.
Checking 'fts.h'... ok.
Checking 'obstack.h'... ok.
Checking 'libintl.h'... ok.
Checking 'ldconfig-stub'... ok.
find: ‘feeds/base’: No such file or directory
Collecting package info: done
find: ‘feeds/base’: No such file or directory
Collecting target info: done
Create index file './feeds/packages.index' 
find: ‘feeds/packages’: No such file or directory
Collecting package info: done
find: ‘feeds/packages’: No such file or directory
Collecting target info: done
Create index file './feeds/luci.index' 
find: ‘feeds/luci’: No such file or directory
Collecting package info: done
find: ‘feeds/luci’: No such file or directory
Collecting target info: done
Create index file './feeds/routing.index' 
Collecting package info: done
Collecting target info: done
Create index file './feeds/telephony.index' 
ERROR: please fix feeds/telephony/net/freeswitch/Makefile - see logs/feeds/telephony/net/freeswitch/dump.txt for details
ERROR: please fix feeds/telephony/net/kamailio/Makefile - see logs/feeds/telephony/net/kamailio/dump.txt for details
Collecting package info: done
Collecting target info: done

**Comment by ksi1110** [comment]
请问哪位知道怎样解决这个问题吗？？？我想编译个插件，已经卡这里三天了😂😂😂

**Comment by ksi1110** [comment]
Hello??? is there anyone who can help???

**Comment by ksi1110** [comment]
master-v23.05，这个标签找不到，改成openwrt-23.05，可以下载成功，但是编译软件仍然报错，重新检查了环境和包，都没有报错，原地放弃，看来这固件也没多少人用，社区活跃度为0，放弃了，转istoreos

**Comment by friendlyarm** [comment]
curl 56 GnuTLS recv error 
这个看上去是网络问题

**Comment by ksi1110** [comment]
香港出口，其他服务没有问题

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
