### ISSUE TITLE
R3S 关闭IP6, LAN 口死活不亮, 分配不到IP, 刷机解决不了! 救砖又缺少RK3566 loader!!!

### ISSUE THREAD

**Issue by gowy222** [friendlyarm/Actions-FriendlyWrt#72]
手动脚本
```
echo "禁用内核中的 IPv6..."
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1
echo "net.ipv6.conf.all.disable_ipv6=1" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.disable_ipv6=1" >> /etc/sysctl.conf
uci set dhcp.@odhcpd[0].maindhcp='1'

 echo "移除网络接口中的 IPv6 地址..."
 ip -6 addr flush dev eth0
 ip -6 addr flush dev br-lan
ip -6 addr flush dev tun0

```

重启之后LAN就不亮了,
然后刷机 TF 固件 21/23版本都不能解决
又刷机 SD-EMMC 21/23版本 同样不起作用...

红灯+wan 正常工作...

就是分配不到IP， LAN 不工作, 刷机也无解..

获取loader: 访问[这里](http://112.124.9.243/dvdfiles/)，进入CPU型号对应的tools目录，下载 MiniLoaderAll.bin
关键里面没有R3S的CPU版本文件... RK3566，救砖都没希望..

咋办??
@friendlyarm 

另外，RESET按钮有啥用? 文档也没说明, 按了也不能恢复..

**Comment by xxs-2** [comment]
1.R3S没有usb网卡，一个RGMII 8211F,一个PCIE 8111H
2.请看文档的4.4.3.3，里面提供的usb固件带了loader
https://wiki.friendlyelec.com/wiki/index.php/NanoPi_R3S/zh

**Comment by Kotevich** [comment]
Same issue. LAN chip driver is not installed out of the box. Only WAN port enabled. Need fix

**Comment by argakon** [comment]
+1 to the problem with lan port issue.
I flashed friendlywrt and lan port doesn't works.
debian/ubuntu images works fine

**Comment by friendlyarm** [comment]
The FriendlyWrt images has been re-uploaded to google drive, I think the lan issue has been solved.
Sorry for the trouble.
